trigger:
- main

variables:
  imageName: azure-pipelines-canary-k8s
  dockerRegistryServiceConnection: azure-pipelines-canary-acr
  containerRegistry: canaryacraniket.azurecr.io
  tag: $(Build.BuildId)

stages:

- stage: Build
  displayName: Build Stage

  jobs:

  - job: Build
    displayName: Build and Push Docker Image

    pool:
      name: azureSubsPool

    steps:

    - script: |
        echo "Build Sources Directory:"
        echo $(Build.SourcesDirectory)

        echo "Current Directory:"
        pwd

        echo "Repository Files:"
        find $(Build.SourcesDirectory) -type f | head -100
      displayName: Debug Repository Structure

    - task: Docker@2
      displayName: Build and Push Image

      env:
        DOCKER_BUILDKIT: 0

      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)

        repository: $(imageName)

        command: buildAndPush

        Dockerfile: $(Build.SourcesDirectory)/app/Dockerfile

        buildContext: $(Build.SourcesDirectory)/app
        addPipelineData: false
        addBaseImageData: false

        tags: |
          $(tag)