trigger:
- main

pool:
  name: azureSubsPool

variables:
  imageName: azure-pipelines-canary-k8s
  acrName: canaryacraniket.azurecr.io
  tag: $(Build.BuildId)

stages:

- stage: Build

  jobs:

  - job: Build

    steps:

    - checkout: self

    - script: |
        docker build \
          -t $(acrName)/$(imageName):$(tag) \
          -f $(Build.SourcesDirectory)/app/Dockerfile \
          $(Build.SourcesDirectory)/app

      displayName: Docker Build

    - script: |
        az acr login --name canaryacraniket

        docker push $(acrName)/$(imageName):$(tag)

      displayName: Docker Push